[build]
    command = "echo 'No build command needed.'"
    base = "/"
    publish = "/"
    functions = "/faas"

[dev]
    port = 18888
    targetPort = 28888
    autoLaunch = true

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 308
    force = true
